### ISSUE TITLE
页面来回切换 第一次可以跳转 两次或多次点击之后没反应

### ISSUE THREAD

**Issue by doinbean** [spencer1994/mpvue-cli#10]
页面来回诶换点击去往首页2次或多次以上 没反应 页面不跳转 只是增加一个class navigator-hove

**Comment by spencer1994** [comment]
@doinbean 我这边没有这种问题，能否贴一下代码我试试？

**Comment by doinbean** [comment]
就是你点击去首页 然后点击去vue示例页面 然后在点击去首页 在点击去vue示例页面  2次循环之后再点击页面不跳转了 使用wx.navigateTo(）也是同样情况

**Comment by spencer1994** [comment]
@doinbean 一般来说不会有这种反复进入页面的需求吧，你用一下redirectTo试试？我下午试试看，可能是mpvue或者是小程序的问题。

**Comment by doinbean** [comment]
电商会有来回跳 并且你这跳了之后去其他页面也不会跳转了 并不是来回两个页面 我试了来回三个页面跳转两次之后也是同样问题 我现在只有就用mpvue 不用router集中写在一起了

**Comment by spencer1994** [comment]
@doinbean 来回跳的话是navigateTo和navigateBack吧，不会来回都是To吧，我这个东西只是简单封装了一下mpvue-quickstart而已，没有做其他操作，讲道理不会有这种卡死的情况发生。你能否贴一下你的代码片段？

**Comment by doinbean** [comment]
我就是用的你的工程 就是在那三个页面路由跳转 log vue示例 首页跳转 
_<a_ href="/pages/counter/index" class="home">去往vue</a>
goto: function () {
        console.log('跳转方法')
        const url = '/pages/index/index'
        wx.navigateTo({ url })
        wx.redirectTo({url})
      }
三种写法点击两次之后都会没反应 我打印了 也进入了跳转方法function 后面也是同样情况不跳转 
是不是 mpvue-entry  默认hash模式变为了history 具体我也不是很清楚 也没找到原因

**Comment by spencer1994** [comment]
@doinbean好的谢谢，我下午试试。晚点给你答复

**Comment by spencer1994** [comment]
@doinbean demo的 <a href=""></a>标签是navigateTo，两个页面切换的时候是 首页-> navigateTo vuex页面 -> navigateTo首页 -> navigateTo vuex页面。这样会卡住的。应该弄成 首页 -> navigateTo vuex页面 -> navigateBack 首页，才对。
这也是我刚才说的，来回切换页面都是navigateTo的话是会有问题的。这样子都是页面进栈会超过10层，[小程序的navigateTo是不能超过10层的](https://developers.weixin.qq.com/miniprogram/dev/api/ui-navigate.html#wxnavigatetoobject)
![image](https://user-images.githubusercontent.com/19463934/42615156-7d4426e0-85db-11e8-87c0-d042bd3b3dd8.png)

我把demo改一下吧，免得误导人了。

**Comment by doinbean** [comment]
我也调查了 这篇博客说微信小程序页面栈只能暂存5个  所以我们可以把一些不需要返回的页面，用wx.redirectTo()来进行跳转，就是相当于打开一个新的栈。我试了原生小程序可以10层 你的工程和mpvue工程只能5层啊  https://blog.csdn.net/LJFPHP/article/details/79240200

**Comment by spencer1994** [comment]
@doinbean 你把自己的appid加上去就可以10层了。体验版的话受限，这个是小程序的锅。

**Comment by doinbean** [comment]
好的 非常感谢解惑 麻烦了
