### ISSUE TITLE
npm run dev 后 dist文件夹下没有app.js app.json等文件

### ISSUE THREAD

**Issue by hghwill** [spencer1994/mpvue-cli#12]
我是用vue init spencer1994/mpvue-cli mpvuesimple 这个的
不知道是什么问题

**Comment by spencer1994** [comment]
@hghwill 官方更新了mpvue-loader1.1.x版本。不兼容老的。你暂时把mpvue-loader的版本回退到1.0.14。

**Comment by spencer1994** [comment]
@hghwill 我现在暂时没空适配这个更新，或者你可以自己看看更新内容，可以先把项目适配1.1.x版本。如果可以的话给我提个pr～感谢！
