### ISSUE TITLE
请教配置问题

### ISSUE THREAD

**Issue by SunJianZhang001** [spencer1994/mpvue-cli#13]
求问，在mpvue项目中写原生wxml,js,json,wxss该如何写配置信息（编译wxml到dist中代码不改变）?

**Comment by spencer1994** [comment]
@SunJianZhang001 最近是在太忙，好久没上github了。我能给你的建议，应该就是用webpack一个copy的插件，直接把相关的代码copy至dist中，但我觉得这样可能不能解决问题，需要尝试一下。

另外，使用了mpvue，我觉得没必要再写原生的wxml，js，json，wxss了。不太明白你需要做这种操作的目的是什么？
