### ISSUE TITLE
app.vue 中的通配符样式 

### ISSUE THREAD

**Issue by bgwd666** [spencer1994/mpvue-cli#14]
... 能不能把那通配符去掉, 我用了一两天, 我说我的界面什么的延时很高, 卡顿感觉, 今天才发现这个通配符, 笑哭.....

**Comment by spencer1994** [comment]
哈哈那是mpvue自带的 我没删 就是个简单demo 觉得卡的话直接删掉就可以了

**Comment by bgwd666** [comment]
我刚学mpvue没几天, app.vue 那里没仔细看, 刚刚才发现的, 哭笑不得. 我一直怀疑用mpvue 写的小程序会这么卡??

**Comment by spencer1994** [comment]
你删吧 本来就要自己改造的 我这里就不动了

**Comment by spencer1994** [comment]
@bgwd666 前几日在开年会，那个效果确实很奇怪，不知道为什么之前官方要那么写，已删除。
