### ISSUE TITLE
能否请教fly封装成这样的用法？

### ISSUE THREAD

**Issue by keycz** [spencer1994/mpvue-cli#15]

**Comment by spencer1994** [comment]
@keycz https://github.com/spencer1994/mpvue-cli/blob/master/template/src/pages/counter/index.vue

这个文件有接口的用法，这个就是个demo。具体的话可以针对自己公司的风格来改造～

**Comment by keycz** [comment]
@spencer1994 这个demo好像是vuex的用法，并没有看出flyio的内容啊。
![image](https://user-images.githubusercontent.com/24972118/51956857-409fac80-2484-11e9-8852-ed52f82e7b7d.png)
这个是怎么使用地址管理的？
