### ISSUE TITLE
是否考虑引入mockjs

### ISSUE THREAD

**Issue by cduyzh** [spencer1994/mpvue-cli#2]
mockjs模拟数据在小程序里有时候也是个必要的事，可以考虑加入到脚手架中，区分下环境引入。

**Comment by spencer1994** [comment]
@cduyzh 我觉得没必要把mock弄到代码里来。你可以试试eolinker。或者自己用koa2搭一个mock数据服务，直接调用接口就可以了。

**Comment by spencer1994** [comment]
这几天比较忙没注意，感谢提issue。
