### ISSUE TITLE
如何添加tabBar呢？

### ISSUE THREAD

**Issue by jansonjoan** [spencer1994/mpvue-cli#4]
请指教

**Comment by spencer1994** [comment]
@jansonjoan 在src/main.js的配置里配上tabbar就可以了，具体看一下小程序的app.json配置文件。实际上src/main.js就是编译成app.json

**Comment by jansonjoan** [comment]
@spencer1994 我试过，在pagePath里的路径找不到，提示不在pages里

**Comment by spencer1994** [comment]
@jansonjoan 你可以看看编译后的dist文件的app.json是否有你的路径。然后确认一下tabbar配置的路径是否需要加“/”。这个tabbar我之前是用过的，没有问题的。

**Comment by jansonjoan** [comment]
@spencer1994 可以了，谢谢
