### ISSUE TITLE
flyio封装请求函数报错

### ISSUE THREAD

**Issue by douhaoi** [spencer1994/mpvue-cli#7]
error  in ./src/store/flyio/request.js

  ✘  http://eslint.org/docs/rules/no-undef  '**_tipConfig**' is not defined
  src\store\flyio\request.js:52:42
          setTimeout(() => { errorFunction( **_tipConfig**, res) }, 0)
                                            ^

  ✘  http://eslint.org/docs/rules/no-undef  '**_tipConfig**' is not defined
  src\store\flyio\request.js:55:40
        setTimeout(() => { errorFunction(**_tipConfig**, err) }, 0)

**Comment by douhaoi** [comment]
删除那个参数就没问题了

**Comment by spencer1994** [comment]
@douhaoi 啊不好意思，字段复制错了。把两个项目搞混了，将_tipConfig改成tipConfig就好了。

**Comment by douhaoi** [comment]
ok

**Comment by spencer1994** [comment]
@douhaoi 我修改了，麻烦你自己改一下了。
