### ISSUE TITLE
添加对原生小程序开发的ui组件的支持

### ISSUE THREAD

**Issue by blackjack0v0** [spencer1994/mpvue-cli#9]
今天看到一个wepack插件支持引入原生小程序组件，感觉有了这个好多原生开发的UI都可以用了
https://github.com/JJJYY/import-weapp-component

然后我又把这个插件和你这个整合了一下......，不过得删除mpvue-entry模块（如果能一起使用就更好了.....），其他模块不受影响。
https://github.com/blackjack0v0/mpvuesimple-quickstart

**Comment by spencer1994** [comment]
@blackjack0v0 https://github.com/mpvue/examples/tree/master/echarts 这里是官方说的，貌似是能在page.json的配置中跟小程序一样可以直接引入组件，感觉已经够用了。

**Comment by blackjack0v0** [comment]
@spencer1994  还有这种操作，厉害了老铁，学习了，多谢！！！

**Comment by spencer1994** [comment]
@blackjack0v0 我还没实际用过，只知道有这个东西，互相学习互相学习。

**Comment by blackjack0v0** [comment]
@spencer1994  那在用entry这个插件，每个文件的using component在哪个位置导入呢？
